import { Roboto } from "next/font/google";
import { Provider } from "react-redux";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import store from "@/store/store";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Provider store={store}>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
